### ISSUE TITLE
Activation Pruner fails ugly when not initiated correctly

### ISSUE THREAD

**Issue by barrh** [NervanaSystems/distiller#123]
When applying Activation Pruner, the script does not collect activations by default, and fails ugly mid-training. Broken?

Expected behavior: pruning by activations works independently of logging the activations.

PyTorch ver.: 1.0

**Comment by barrh** [comment]
Log file for this run: /my_checkpoints
distiller_filters/2019.01.10-171300/2019.01.10-171300.log
Traceback (most recent call last):
  File "examples/classifier_compression/compress_classifier.py", line 821, in <module>
    main()
  File "examples/classifier_compression/compress_classifier.py", line 400, in main
    compression_scheduler.on_epoch_begin(epoch)
  File "/distiller/distiller/scheduler.py", line 112, in on_epoch_begin
    policy.on_epoch_begin(self.model, self.zeros_mask_dict, meta)
  File "/distiller/distiller/policy.py", line 134, in on_epoch_begin
    self.pruner.set_param_mask(param, param_name, zeros_mask_dict, meta)
  File "/distiller/distiller/pruning/automated_gradual_pruner.py", line 59, in set_param_mask
    self.prune_to_target_sparsity(param, param_name, zeros_mask_dict, target_sparsity, meta['model'])
  File "/distiller/distiller/pruning/automated_gradual_pruner.py", line 96, in prune_to_target_sparsity
    self.pruner.prune_to_target_sparsity(param, param_name, zeros_mask_dict, target_sparsity, model)
  File "/distiller/distiller/pruning/ranked_structures_pruner.py", line 75, in prune_to_target_sparsity
    self.prune_group(target_sparsity, param, param_name, zeros_mask_dict, model, binary_map)
  File "/distiller/distiller/pruning/ranked_structures_pruner.py", line 327, in prune_group
    binary_map = self.rank_and_prune_filters(fraction_to_prune, param, param_name, zeros_mask_dict, model, binary_map)
  File "/distiller/distiller/pruning/ranked_structures_pruner.py", line 341, in rank_and_prune_filters
    "\nMake sure to use SummaryActivationStatsCollector(\"apoz_channels\")" % fq_name)
ValueError: Could not find attribute 'apoz_channels' in module module.layer2.0.relu2
Make sure to use SummaryActivationStatsCollector("apoz_channels")
Command exited with non-zero status 1
272891.43user 32285.65system 13:54:12elapsed 609%CPU (0avgtext+0avgdata 11796804maxresident)k
152inputs+12226880outputs (9major+5768979710minor)pagefaults 0swaps

(Note that the line numbers might not be exact since I'm running it on modified code base)

**Comment by nzmora** [comment]
Currently we have this documentation: [Collecting activations statistics](https://nervanasystems.github.io/distiller/usage/index.html#collecting-activations-statistics).
