### ISSUE TITLE
amc problem

### ISSUE THREAD

**Issue by HKLee2040** [NervanaSystems/distiller#237]
Kernel: 4.15.0-47-generic
Python: 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
PyTorch: 1.0.1
Numpy: 1.16.3
Git commit: 8c5de42cf08e8d32b966a570c207039cb799a528
Command line: compress_classifier.py --arch=plain20_cifar ../../../data.cifar10 --resume=../cifar10/checkpoint.plain20_cifar.pth.tar --lr=0.05 --amc --amc-protocol=mac-constrained --amc-target-density=0.5 -p=50 --amc-agent-algo ClippedPPO-discrete
Got the following error message:

Traceback (most recent call last):
  File "compress_classifier.py", line 783, in <module>
    main()
  File "compress_classifier.py", line 193, in main
    return automated_deep_compression(model, criterion, optimizer, pylogger, args)
  File "compress_classifier.py", line 694, in automated_deep_compression
    adc.do_adc(model, args, optimizer_data, validate_fn, save_checkpoint_fn, train_fn)
  File "/media/walker/DATA/work/new_quant/distiller/examples/automated_deep_compression/__init__.py", line 5, in do_adc
    do_adc_internal(model, args, optimizer_data, validate_fn, save_checkpoint_fn, train_fn)
  File "/media/walker/DATA/work/new_quant/distiller/examples/automated_deep_compression/ADC.py", line 309, in do_adc_internal
    graph_manager.create_graph(task_parameters)
  File "/media/walker/DATA/work/new_quant/env/lib/python3.5/site-packages/rl_coach/graph_managers/graph_manager.py", line 144, in create_graph
    self.level_managers, self.environments = self._create_graph(task_parameters)
  File "/media/walker/DATA/work/new_quant/env/lib/python3.5/site-packages/rl_coach/graph_managers/basic_rl_graph_manager.py", line 51, in _create_graph
    visualization_parameters=self.visualization_parameters)
  File "/media/walker/DATA/work/new_quant/env/lib/python3.5/site-packages/rl_coach/environments/gym_environment.py", line 324, in __init__
    if not isinstance(self.env.observation_space, gym.spaces.dict_space.Dict):
AttributeError: module 'gym.spaces' has no attribute 'dict_space'

The version of gym is 0.12.1

**Comment by dingqingy** [comment]
I got this problem recently as well. It seems like the problem is `pip install rl_coach` does not install the lastest rl_coach. If you install rl_coach from the github repo, the problem should be solved.

See also https://github.com/NervanaSystems/coach/issues/269

**Comment by HKLee2040** [comment]
@dingqingy Yes, you are right!  The problem is solved if I install rl_coach from github repo.
Thanks!
