### ISSUE TITLE
Please take a look at the FAQ before opening an issue

### ISSUE THREAD

**Issue by guyjacob** [NervanaSystems/distiller#242]
https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)

**Comment by Blue-Eagle-10** [comment]
I have installed all the environments according to the readme. When I run this 8-bit quantized code<python compress_classifier.py -a resnet20_cifar ../../../data.cifar10 --resume ../ssl/checkpoints/checkpoint_trained_dense.pth.tar --quantize-eval --evaluate>, I get the following error. How can I solve this problem?

Traceback (most recent call last):
File "compress_classifier.py", line 210, in 
main()
File "compress_classifier.py", line 74, in main
args = parser.add_cmdline_args(classifier.init_classifier_compression_arg_parser()).parse_args()
AttributeError: module 'parser' has no attribute 'add_cmdline_args'

**Comment by Coderx7** [comment]
@Blue-Eagle-10 I faced this on windows, you need to be on linux I guess in order not to face this error.

**Comment by Blue-Eagle-10** [comment]
@Coderx7 thank you very much!
