### ISSUE TITLE
Quantization-Aware Training about DoReFa

### ISSUE THREAD

**Issue by tzc1994** [NervanaSystems/distiller#248]
HI, How should I use the Quantization-Aware Training such as DoReFa?
The terminal command is right?
**python3 compress_classifier.py -a alexnet /ImageNet_Share/ --compress=/home/tzc/distiller/examples/quantization/quant_aware_train/alexnet_bn_dorefa.yaml**
But I meet this error：
FATAL Parsing error!
{
"quantizer": {
"instance_name": "dorefa_quantizer"
},
"starting_epoch": 0,
"ending_epoch": 200,
"frequency": 1
}
Exception: <class 'TypeError'> unsupported operand type(s) for ** or pow(): 'int' and 'NoneType'

Log file for this run: /home/tzc/distiller/examples/classifier_compression/logs/2019.05.09-115537/2019.05.09-115537.log
Traceback (most recent call last):
File "compress_classifier.py", line 776, in 
main()
File "compress_classifier.py", line 235, in main
(start_epoch-1) if args.resumed_checkpoint_path else None)
File "/home/tzc/distiller/distiller/config.py", line 148, in file_config
return dict_config(model, optimizer, sched_dict, scheduler, resumed_epoch)
File "/home/tzc/distiller/distiller/config.py", line 93, in dict_config
policy = distiller.QuantizationPolicy(quantizer)
File "/home/tzc/distiller/distiller/policy.py", line 226, in init
self.quantizer.quantize_params()
File "/home/tzc/distiller/distiller/quantization/quantizer.py", line 277, in quantize_params
q_param = self.param_quantization_fn(getattr(ptq.module, ptq.fp_attr_name), ptq)
File "/home/tzc/distiller/distiller/quantization/clipped_linear.py", line 133, in dorefa_quantize_param
scale, zero_point = asymmetric_linear_quantization_params(param_meta.num_bits, 0, 1, signed=False)
File "/home/tzc/distiller/distiller/quantization/q_utils.py", line 65, in asymmetric_linear_quantization_params
n = 2 ** num_bits - 1
TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'NoneType'

**Comment by guyjacob** [comment]
@tzc1994 Sorry for the late reply. Your command line is correct, it's indeed a bug. Thanks for catching this!
Fixed in https://github.com/NervanaSystems/distiller/commit/4c16369057e5dde41d0ac5ee0dca1a8cc67ddc36.

**Comment by brisker** [comment]
@tzc1994 
@guyjacob 
If running `python3 compress_classifier.py -a alexnet /ImageNet_Share/ --compress=/home/tzc/distiller/examples/quantization/quant_aware_train/alexnet_bn_dorefa.yaml`,
do we need to modify the compress_classifier.py ?
