### ISSUE TITLE
How to export quantized model to onnx

### ISSUE THREAD

**Issue by tianylijun** [NervanaSystems/distiller#283]

**Comment by tianylijun** [comment]
For fp32 model, follow cmd work ok

_python compress_classifier.py -a resnet50 --pretrained /home/lijun/ImageNet --evaluate --out-dir out_resnet50_onnx --export-onnx_

For quantized model

_python compress_classifier.py -a resnet50 --resume-from out_resnet50/2019.06.11-111347/quantized_checkpoint.pth.tar ~/ImageNet --evaluate --out-dir out_resnet50_onnx --export-onnx_

Traceback (most recent call last):
  File "compress_classifier.py", line 794, in <module>
    main()
  File "compress_classifier.py", line 208, in main
    args.dataset, add_softmax=True, verbose=False)
  File "/home/lee/distiller/distiller/model_summaries.py", line 474, in export_img_classifier_to_onnx
    torch.onnx.export(non_para_model, dummy_input, onnx_fname, **kwargs)
  File "/home/lee/distiller/env/lib/python3.5/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/lee/distiller/env/lib/python3.5/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/lee/distiller/env/lib/python3.5/site-packages/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/home/lee/distiller/env/lib/python3.5/site-packages/torch/onnx/utils.py", line 227, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type)
  File "/home/lee/distiller/env/lib/python3.5/site-packages/torch/onnx/utils.py", line 155, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lee/distiller/env/lib/python3.5/site-packages/torch/onnx/__init__.py", line 52, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lee/distiller/env/lib/python3.5/site-packages/torch/onnx/utils.py", line 504, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
TypeError: zeros_like() takes 2 positional arguments but 5 were given (occurred when translating zeros_like)

**Comment by guyjacob** [comment]
Hi @tianylijun, indeed this is still not supported. Please see #255 for more details. I'm closing this one, feel free to ask or comment there.
