### ISSUE TITLE
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

### ISSUE THREAD

**Issue by tjussh** [NervanaSystems/distiller#358]
hi, 
when i do filter prune my network, i got this error. 
Traceback (most recent call last):
  File "/home/distiller/examples/DN/train_0820.py", line 446, in <module>
    compression_scheduler.on_minibatch_begin(epoch, n_count, steps_per_epoch, optimizer)
  File "/home/distiller/distiller/scheduler.py", line 132, in on_minibatch_begin
    self.zeros_mask_dict, meta, optimizer)
  File "/home/distiller/distiller/thinning.py", line 418, in on_minibatch_begin
    self.__apply(model, zeros_mask_dict, optimizer)
  File "/home/distiller/distiller/thinning.py", line 409, in __apply
    self.thinning_func(model, zeros_mask_dict, self.arch, self.dataset, optimizer=optimizer)
  File "/home/distiller/distiller/thinning.py", line 199, in remove_filters
    sgraph = create_graph(dataset, model)
  File "/home/distiller/distiller/thinning.py", line 69, in create_graph
    return SummaryGraph(model, dummy_input)
  File "/home/distiller/distiller/summary_graph.py", line 121, in __init__
    torch.onnx._optimize_trace(trace, torch.onnx.OperatorExportTypes.ONNX)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 40, in _optimize_trace
    trace.set_graph(utils._optimize_graph(trace.graph(), operator_export_type))
  File "/home/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/anaconda3/lib/python3.7/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/anaconda3/lib/python3.7/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

my Environmental configuration is：
Ubuntu 16.04， CUDA9.0， python3.7，torch==1.1.0

my network have a nn.UpsamplingBilinear2d Module, maybe it's a bug in pytorch 1.1.0

**Comment by tjussh** [comment]
i refer to this commit [pytorch/pytorch@11845cf](https://github.com/pytorch/pytorch/commit/11845cf2440c1abb0cb117bcee9532b26573e9c9), the bug fixed.

**Comment by tjussh** [comment]
i refer to this commit pytorch/pytorch@11845cf, the bug fixed.
