### ISSUE TITLE
yolov3 

### ISSUE THREAD

**Issue by zyxcambridge** [NervanaSystems/distiller#442]
/root/anaconda3/envs/distiller/bin/python /media/root/code/distiller/examples/yolov3/test-distiller.py
Namespace(batch_size=16, cfg='cfg/yolov3-spp.cfg', conf_thres=0.001, data='data/coco.data', device='', img_size=416, iou_thres=0.5, nms_thres=0.5, save_json=False, weights='weights/yolov3-spp.weights')
Using CUDA device0 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=10986MB)

5000
======:
               Class    Images   Targets         P         R   mAP@0.5        F1:   0%|          | 0/313 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/media/root/code/distiller/examples/yolov3/test-distiller.py", line 291, in <module>
    opt.save_json or (opt.data == 'data/coco.data'))
  File "/media/root/code/distiller/examples/yolov3/test-distiller.py", line 254, in test
    collect_quant_stats(model_copy, eval_for_stats, save_dir='.')
  File "/media/root/code/distiller/distiller/data_loggers/collector.py", line 814, in collect_quant_stats
    test_fn(model=model)
  File "/media/root/code/distiller/examples/yolov3/test-distiller.py", line 252, in eval_for_stats
    evaluate(model, output + '.temp', num_batches=None, dataloader=None)
  File "/media/root/code/distiller/examples/yolov3/test-distiller.py", line 118, in evaluate
    inf_out, train_out = model(imgs)  # inference and training outputs
  File "/root/anaconda3/envs/distiller/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/root/code/yolov3/models.py", line 262, in forward
    x = module(x, img_size)
  File "/root/anaconda3/envs/distiller/lib/python3.6/site-packages/torch/nn/modules/module.py", line 543, in __call__
    hook_result = hook(self, input, result)
  File "/media/root/code/distiller/distiller/data_loggers/collector.py", line 582, in _activation_stats_cb
    update_record(module.quant_stats.inputs[idx], input)
  File "/media/root/code/distiller/distiller/data_loggers/collector.py", line 534, in update_record
    if tensor.dtype not in [torch.float16, torch.float32, torch.float64]:
AttributeError: 'torch.Size' object has no attribute 'dtype'

**Comment by levzlotnik** [comment]
Hi @zyxcambridge ,

I assume that since this is yolo_v3, you somehow pass `torch.Size` as some kind of input to a layer / output this `torch.Size` that is supposed to indicate either a Bounding Box or some other value like that to reshape another tensor into.  
I suggest converting it into `torch.Tensor` (with something like `torch.tensor(s)`) if you'd like to gather stats for this tensor.   
However for me it seems that there's no need to gather stats for this value (what will mean/std/min/max mean for a value of torch.Size?), and so even if you gather it by converting into a tensor - try to ignore it afterwards when using the quant_stats in `PostTrainLinearQuantizer`.   
Another workaround - in `QuantCalibrationStatsCollector._activation_stats_cb.update_record()` check for the type of the input and skip it if it isn't a tensor - i.e. `if not isinstance(tensor, torch.Tensor): return`.
Let me know if you need to figure out something else.

Thanks,
Lev

**Comment by levzlotnik** [comment]
Hi,

Closing this issue due to staleness. Feel free to reopen if there are any further questions.
