### ISSUE TITLE
Problems when use APOZ to purn vgg11_bn_cifar

### ISSUE THREAD

**Issue by zxj-123** [NervanaSystems/distiller#459]
Thank you in advance for your work
my yaml is：
version: 1

pruners:
  low_pruner1:
    class: ActivationAPoZRankedFilterPruner
    group_type: Filters
    desired_sparsity: 0.189
    weights: ['features.4.weight', 'features.8.weight', 'features.11.weight']
policies:
    - pruner:
        instance_name : low_pruner1
      epochs: [1]

Log file for this run: /home/logs/2020.01.07-093447/2020.01.07-093447.log
Traceback (most recent call last):
  File "/home/distiller-master/examples/classifier_compression/compress_classifier.py", line 209, in <module>
    main()
  File "/home/distiller-master/examples/classifier_compression/compress_classifier.py", line 78, in main
    app.run_training_loop()
  File "/home/zbh/distiller-master/distiller/apputils/image_classifier.py", line 192, in run_training_loop
    top1, top5, loss = self.train_validate_with_scheduling(epoch)
  File "/home/zbh/distiller-master/distiller/apputils/image_classifier.py", line 128, in train_validate_with_scheduling
    self.compression_scheduler.on_epoch_begin(epoch)
  File "/home/distiller-master/distiller/scheduler.py", line 71, in on_epoch_begin
    **kwargs)
  File "/home/distiller-master/distiller/policy.py", line 208, in on_epoch_begin
    self.pruner.set_param_mask(param, param_name, zeros_mask_dict, meta)
  File "/home/distiller-master/distiller/pruning/ranked_structures_pruner.py", line 77, in set_param_mask
    return self._set_param_mask_by_sparsity_target(param, param_name, zeros_mask_dict, fraction_to_prune, model)
  File "/home/distiller-master/distiller/pruning/ranked_structures_pruner.py", line 95, in _set_param_mask_by_sparsity_target
    self.prune_group(target_sparsity, param, param_name, zeros_mask_dict, model, binary_map)
  File "/home/distiller-master/distiller/pruning/ranked_structures_pruner.py", line 338, in prune_group
    zeros_mask_dict, model, binary_map)
  File "/home/distiller-master/distiller/pruning/ranked_structures_pruner.py", line 353, in rank_and_prune_filters
    format(self.activation_rank_criterion, fq_name, self.activation_rank_criterion))
ValueError: Could not find attribute "apoz_channels" in module %s
Make sure to use SummaryActivationStatsCollector("features.4")

command：python /home/distiller-master/examples/classifier_compression/compress_classifier.py --arch vgg11_bn_cifar /home/DeeplearningData/cifar-10/cifar-10-batches-py -p=500 --lr=0.1 --epochs=200 --compress=vgg11.yaml -j=6 --momentum=0.9 --weight-decay=0.0005 -b=128 --validation-split=0 --act-stats=test

thanks a lot

**Comment by nzmora** [comment]
Hi @zxj-123 ,

I can't recreate this issue - please send the log file for this execution.

Thanks,
Neta
