### ISSUE TITLE
A problem in AMC

### ISSUE THREAD

**Issue by smxzxcghl** [NervanaSystems/distiller#461]
Hi,
Thank you for this library. 
I met a problem when using AMC. I try command line like this :

`time python3 ../../classifier_compression/multi-run.py ./resnet20-ddpg-private. amc.py  --arch=resnet20_cifar  ../../../../../data.cifar10 --resume=../../ssl/checkpoints/checkpoint_trained_dense.pth.tar --amc-protocol=mac-constrained --amc-action-range 0.05 1.0 --amc-target-density=0.5 -p=50 --etes=0.075 --amc-ft-epochs=0 --amc-prune-pattern=channels --amc-prune-method=fm-reconstruction --amc-agent-algo=DDPG --amc-cfg=auto_compression_channels.yaml --amc-rllib=hanlab -j=1`

and this：

`python3 amc.py --arch=resnet20_cifar  ../../../../../data.cifar10 --resume=../../ssl/checkpoints/checkpoint_trained_dense.pth.tar --amc-protocol=mac-constrained --amc-action-range 0.05 1.0 --amc-target-density=0.5 -p=50 --etes=0.075 --amc-ft-epochs=0 --amc-prune-pattern=channels --amc-prune-method=fm-reconstruction --amc-agent-algo=DDPG --amc-cfg=auto_compression_channels.yaml --amc-rllib=hanlab -j=1 --gpus=1`

The same error occurred:

```
==> Collecting input/ouptput feature-map pairs
Traceback (most recent call last):
  File "amc.py", line 187, in <module>
    main()
  File "amc.py", line 64, in main
    return app.train_auto_compressor()
  File "amc.py", line 55, in train_auto_compressor
    return train_auto_compressor(self.model, self.args, optimizer_data, validate_fn, save_checkpoint_fn, train_fn)
  File "amc.py", line 138, in train_auto_compressor
    env1 = create_environment()
  File "amc.py", line 134, in create_environment
    env = DistillerWrapperEnvironment(model, app_args, amc_cfg, services)
  File "/root/ghl/distiller/examples/auto_compression/amc/environment.py", line 112, in __init__
    self._collect_fm_reconstruction_samples(modules_list)
  File "/root/ghl/distiller/examples/auto_compression/amc/environment.py", line 136, in _collect_fm_reconstruction_samples
    n_points_per_fm=self.amc_cfg.n_points_per_fm))
  File "/root/ghl/distiller/examples/auto_compression/amc/utils/features_collector.py", line 63, in collect_intermediate_featuremap_samples
    forward_fn()
  File "/root/ghl/distiller/examples/auto_compression/amc/utils/net_wrapper.py", line 167, in validate
    top1, top5, vloss = self.services.validate_fn(model=self.model)
  File "/root/ghl/distiller/distiller/apputils/image_classifier.py", line 657, in test
    torch.onnx.export(non_para_model, dummy_input, onnx_fname)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/utils.py", line 249, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/utils.py", line 206, in _trace_and_get_graph_from_model
    trace, torch_out, inputs_states = torch.jit.get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/jit/__init__.py", line 275, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/jit/__init__.py", line 352, in forward
    out = self.inner(*trace_inputs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/ghl/distiller/distiller/apputils/image_classifier.py", line 655, in <lambda>
    non_para_model.forward = lambda input: softmax(non_para_model.original_forward(input))
  File "/root/ghl/distiller/distiller/models/cifar10/resnet_cifar.py", line 142, in forward
    x = self.layer1(x)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/ghl/distiller/distiller/models/cifar10/resnet_cifar.py", line 77, in forward
    out = self.conv2(out)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 543, in __call__
    hook_result = hook(self, input, result)
  File "/root/ghl/distiller/distiller/pruning/ranked_structures_pruner.py", line 606, in cache_featuremaps_fwd_hook
    pts = randx * w_out + randy
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray
```
It is strange that I ran the code successfully yesterday. But today it doesn't work at all. It really confuses me.
The environment is Ubuntu16.04, Nvidia Tesla M40, cuda9.0, cudnn7.3, python 3.5.2, pytorch1.3.1, numpy1.17.4. And I use the newest distiller.
Could anyone tell me the reason and how to fix it? Thank you very much.

**Comment by nzmora** [comment]
Hi @smxzxcghl,

Please make sure that you haven't made local changes, and then send the log file of this run.
Cheers,
Neta

**Comment by smxzxcghl** [comment]
Hi， @nzmora 
Thank you for your reply. 
I replace the auto_compression directory with the one recloned from git, but the problem remain unsolved. I copy the whole log file：
`2020-01-19 14:42:45,710 - Log file for this run: /root/ghl/distiller/examples/auto_compression/amc/logs/2020.01.19-144245/2020.01.19-144245.log
2020-01-19 14:42:45,711 - Number of CPUs: 56
2020-01-19 14:42:45,741 - Number of GPUs: 2
2020-01-19 14:42:45,742 - CUDA version: 9.0.176
2020-01-19 14:42:45,742 - CUDNN version: 7300
2020-01-19 14:42:45,743 - Kernel: 3.10.0-693.2.2.el7.x86_64
2020-01-19 14:42:45,743 - Python: 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
2020-01-19 14:42:45,743 - pip freeze: {'pyyaml': '5.2', 'bqplot': '0.11.5', 'kiwisolver': '1.1.0', 'zipp': '0.6.0', 'chardet': '3.0.4', 'atomicwrites': '1.3.0', 'keras-applications': '1.0.8', 'keras-preprocessing': '1.1.0', 'setuptools': '44.0.0', 'pickleshare': '0.7.5', 'munch': '2.5.0', 'traittypes': '0.2.1', 'werkzeug': '0.16.0', 'urllib3': '1.25.7', 'google-pasta': '0.1.8', 'testpath': '0.4.4', 'jupyter-client': '5.3.4', 'defusedxml': '0.6.0', 'ninja': '1.9.0.post1', 'prompt-toolkit': '2.0.10', 'pathlib2': '2.3.5', 'entrypoints': '0.3', 'cycler': '0.10.0', 'torchfile': '0.1.0', 'packaging': '19.2', 'xlsxwriter': '1.2.6', 'bleach': '3.1.0', 'terminado': '0.8.3', 'backcall': '0.1.0', 'prometheus-client': '0.7.1', 'scipy': '1.3.3', 'qtconsole': '4.6.0', 'h5py': '2.10.0', 'ipython': '7.9.0', 'pexpect': '4.7.0', 'opt-einsum': '3.1.0', 'torch': '1.3.1+ee77ccb', 'typing': '3.7.4.1', 'jsonpointer': '2.0', 'tornado': '6.0.3', 'torchnet': '0.0.4', 'termcolor': '1.1.0', 'pygments': '2.5.2', 'gast': '0.2.2', 'matplotlib': '3.0.3', 'grpcio': '1.25.0', 'scikit-build': '0.10.0', 'visdom': '0.1.8.9', 'idna': '2.8', 'parso': '0.5.2', 'requests': '2.22.0', 'send2trash': '1.5.0', 'ipython-genutils': '0.2.0', 'jinja2': '2.10.3', 'widgetsnbextension': '3.4.2', 'tensorflow': '1.15.0', 'pytz': '2019.3', 'jupyter-core': '4.6.1', 'graphviz': '0.10.1', 'pretrainedmodels': '0.7.4', 'markdown': '3.1.1', 'pycparser': '2.19', 'smmap2': '2.0.5', 'astor': '0.8.1', 'jupyter-console': '6.0.0', 'future': '0.18.2', 'tensorboard': '1.15.0', 'websocket-client': '0.56.0', 'more-itertools': '8.0.2', 'six': '1.13.0', 'scikit-learn': '0.21.2', 'jsonschema': '3.2.0', 'absl-py': '0.8.1', 'attrs': '19.3.0', 'pyrsistent': '0.15.6', 'pandas': '0.24.2', 'wheel': '0.33.6', 'ipykernel': '5.1.3', 'distiller': '0.4.0rc0', 'traitlets': '4.3.3', 'pydot': '1.4.1', 'markupsafe': '1.1.1', 'numpy': '1.17.4', 'ipywidgets': '7.4.2', 'gitdb2': '2.0.6', 'pandocfilters': '1.4.2', 'python-dateutil': '2.8.1', 'wcwidth': '0.1.7', 'pkg-resources': '0.0.0', 'decorator': '4.4.1', 'wrapt': '1.11.2', 'gym': '0.12.5', 'tabulate': '0.8.3', 'gitpython': '2.1.11', 'pytest': '4.6.7', 'ptyprocess': '0.6.0', 'pluggy': '0.13.1', 'importlib-metadata': '1.3.0', 'jsonpatch': '1.24', 'qgrid': '1.1.1', 'pyparsing': '2.4.5', 'nbformat': '4.4.0', 'webencodings': '0.5.1', 'tqdm': '4.33.0', 'jupyter': '1.0.0', 'notebook': '6.0.2', 'pip': '19.3.1', 'tensorflow-estimator': '1.15.1', 'pyglet': '1.4.8', 'certifi': '2019.11.28', 'pillow': '6.2.1', 'joblib': '0.14.1', 'mistune': '0.8.4', 'jedi': '0.15.1', 'protobuf': '3.11.1', 'nbconvert': '5.6.1', 'cffi': '1.13.2', 'torchvision': '0.4.2+cu92', 'py': '1.8.0', 'pyzmq': '18.1.1'}
2020-01-19 14:42:45,833 - Git is dirty
2020-01-19 14:42:45,834 - Active Git branch: master
2020-01-19 14:42:45,868 - Git commit: 4717596112b70600bb3ac54c7a23a55abfea113e
2020-01-19 14:42:45,868 - Command line: amc.py --arch=resnet20_cifar ../../../../../data.cifar10 --resume=../../ssl/checkpoints/checkpoint_trained_dense.pth.tar --amc-protocol=mac-constrained --amc-action-range 0.05 1.0 --amc-target-density=0.5 -p=50 --etes=0.075 --amc-ft-epochs=0 --amc-prune-pattern=channels --amc-prune-method=fm-reconstruction --amc-agent-algo=DDPG --amc-cfg=auto_compression_channels.yaml --amc-rllib=hanlab -j=1
2020-01-19 14:42:45,870 - Random seed: 52572
2020-01-19 14:42:45,887 - => created a resnet20_cifar model with the cifar10 dataset
2020-01-19 14:42:47,886 - The "--resume" flag is deprecated. Please use "--resume-from=YOUR_PATH" instead.
2020-01-19 14:42:47,886 - If you wish to also reset the optimizer, call with: --reset-optimizer
2020-01-19 14:42:47,886 - => loading checkpoint ../../ssl/checkpoints/checkpoint_trained_dense.pth.tar
2020-01-19 14:42:47,894 - => Checkpoint contents:
+-------------------+-------------+----------------+
| Key               | Type        | Value          |
|-------------------+-------------+----------------|
| arch              | str         | resnet20_cifar |
| best_top1         | float       | 92.54          |
| compression_sched | dict        |                |
| epoch             | int         | 179            |
| optimizer         | dict        |                |
| state_dict        | OrderedDict |                |
+-------------------+-------------+----------------+

2020-01-19 14:42:47,895 - Loaded compression schedule from checkpoint (epoch 179)
2020-01-19 14:42:47,902 - Optimizer could not be loaded from checkpoint.
2020-01-19 14:42:47,903 - => loaded checkpoint '../../ssl/checkpoints/checkpoint_trained_dense.pth.tar' (epoch 179)
2020-01-19 14:42:47,903 - AMC: fixed_subset=True	sequential=True
2020-01-19 14:42:50,071 - Dataset sizes:
	training=45000
	validation=5000
	test=750
2020-01-19 14:42:52,352 - Resetting the environment (init_only=True)
2020-01-19 14:42:52,373 - AMC configuration:
2020-01-19 14:42:52,373 - 	modules_dict : OrderedDict([('mobilenet', ['module.model.1.3', 'module.model.2.3', 'module.model.3.3', 'module.model.4.3', 'module.model.5.3', 'module.model.6.3', 'module.model.7.3', 'module.model.8.3', 'module.model.9.3', 'module.model.10.3', 'module.model.11.3', 'module.model.12.3', 'module.model.13.3', 'module.fc']), ('mobilenet_v2', ['module.features.1.conv.1', 'module.features.2.conv.0.0', 'module.features.2.conv.2', 'module.features.3.conv.2', 'module.features.4.conv.2', 'module.features.5.conv.2', 'module.features.6.conv.2', 'module.features.7.conv.2', 'module.features.8.conv.2', 'module.features.9.conv.2', 'module.features.10.conv.2', 'module.features.11.conv.2', 'module.features.12.conv.2', 'module.features.13.conv.2', 'module.features.14.conv.2', 'module.features.15.conv.2', 'module.features.16.conv.2', 'module.features.17.conv.2', 'module.features.18.0']), ('resnet50', ['module.layer1.0.conv3', 'module.layer1.0.conv2', 'module.layer1.1.conv3', 'module.layer1.1.conv2', 'module.layer1.2.conv3', 'module.layer1.2.conv2', 'module.layer2.0.conv3', 'module.layer2.0.conv2', 'module.layer2.1.conv3', 'module.layer2.1.conv2', 'module.layer2.2.conv3', 'module.layer2.2.conv2', 'module.layer2.3.conv3', 'module.layer2.3.conv2', 'module.layer3.0.conv3', 'module.layer3.0.conv2', 'module.layer3.1.conv3', 'module.layer3.1.conv2', 'module.layer3.2.conv3', 'module.layer3.2.conv2', 'module.layer3.3.conv3', 'module.layer3.3.conv2', 'module.layer3.4.conv3', 'module.layer3.4.conv2', 'module.layer3.5.conv3', 'module.layer3.5.conv2', 'module.layer4.0.conv3', 'module.layer4.0.conv2', 'module.layer4.1.conv3', 'module.layer4.1.conv2', 'module.layer4.2.conv3', 'module.layer4.2.conv2']), ('resnet20_cifar', ['module.layer1.0.conv2', 'module.layer1.1.conv2', 'module.layer1.2.conv2', 'module.layer2.0.conv2', 'module.layer2.1.conv2', 'module.layer2.2.conv2', 'module.layer3.0.conv2', 'module.layer3.1.conv2', 'module.layer3.2.conv2']), ('resnet56_cifar', ['module.layer1.0.conv2', 'module.layer1.1.conv2', 'module.layer1.2.conv2', 'module.layer1.3.conv2', 'module.layer1.4.conv2', 'module.layer1.5.conv2', 'module.layer1.6.conv2', 'module.layer1.7.conv2', 'module.layer1.8.conv2', 'module.layer2.0.conv2', 'module.layer2.1.conv2', 'module.layer2.2.conv2', 'module.layer2.3.conv2', 'module.layer2.4.conv2', 'module.layer2.5.conv2', 'module.layer2.6.conv2', 'module.layer2.7.conv2', 'module.layer2.8.conv2', 'module.layer3.0.conv2', 'module.layer3.1.conv2', 'module.layer3.2.conv2', 'module.layer3.3.conv2', 'module.layer3.4.conv2', 'module.layer3.5.conv2', 'module.layer3.6.conv2', 'module.layer3.7.conv2', 'module.layer3.8.conv2']), ('plain20_cifar', ['module.layer1.0.conv1', 'module.layer1.0.conv2', 'module.layer1.1.conv1', 'module.layer1.1.conv2', 'module.layer1.2.conv1', 'module.layer1.2.conv2', 'module.layer2.0.conv1', 'module.layer2.0.conv2', 'module.layer2.1.conv1', 'module.layer2.1.conv2', 'module.layer2.2.conv1', 'module.layer2.2.conv2', 'module.layer3.0.conv1', 'module.layer3.0.conv2', 'module.layer3.1.conv1', 'module.layer3.1.conv2', 'module.layer3.2.conv1', 'module.layer3.2.conv2', 'module.fc']), ('simplenet_mnist', ['module.conv2'])])
2020-01-19 14:42:52,374 - 	action_constrain_fn : <function mac_constrained_clamp_action at 0x7f0737b1fd08>
2020-01-19 14:42:52,374 - 	action_range : [0.05, 1.0]
2020-01-19 14:42:52,374 - 	agent_algo : DDPG
2020-01-19 14:42:52,374 - 	save_chkpts : False
2020-01-19 14:42:52,374 - 	n_points_per_fm : 10
2020-01-19 14:42:52,374 - 	ddpg_cfg : {'heatup_noise': 0.5, 'num_heatup_episodes': 100, 'training_noise_decay': 0.95, 'num_training_episodes': 700, 'initial_training_noise': 0.5, 'actor_lr': 0.0001, 'critic_lr': 0.001}
2020-01-19 14:42:52,374 - 	group_size : 1
2020-01-19 14:42:52,374 - 	reward_fn : <function amc_mac_constrained_reward_fn at 0x7f0737b1fb70>
2020-01-19 14:42:52,374 - 	target_density : 0.5
2020-01-19 14:42:52,374 - 	protocol : mac-constrained
2020-01-19 14:42:52,374 - 	reward_frequency : None
2020-01-19 14:42:52,374 - 	num_ft_epochs : 0
2020-01-19 14:42:52,374 - 	ranking_noise : 0.0
2020-01-19 14:42:52,375 - 	pruning_pattern : channels
2020-01-19 14:42:52,375 - 	pruning_method : fm-reconstruction
2020-01-19 14:42:52,375 - 	ft_frequency : None
2020-01-19 14:42:52,376 - ==> Collecting input/ouptput feature-map pairs
2020-01-19 14:43:07,067 - Traceback (most recent call last):
  File "amc.py", line 186, in <module>
    main()
  File "amc.py", line 63, in main
    return app.train_auto_compressor()
  File "amc.py", line 54, in train_auto_compressor
    return train_auto_compressor(self.model, self.args, optimizer_data, validate_fn, save_checkpoint_fn, train_fn)
  File "amc.py", line 137, in train_auto_compressor
    env1 = create_environment()
  File "amc.py", line 133, in create_environment
    env = DistillerWrapperEnvironment(model, app_args, amc_cfg, services)
  File "/root/ghl/distiller/examples/auto_compression/amc/environment.py", line 112, in __init__
    self._collect_fm_reconstruction_samples(modules_list)
  File "/root/ghl/distiller/examples/auto_compression/amc/environment.py", line 136, in _collect_fm_reconstruction_samples
    n_points_per_fm=self.amc_cfg.n_points_per_fm))
  File "/root/ghl/distiller/examples/auto_compression/amc/utils/features_collector.py", line 63, in collect_intermediate_featuremap_samples
    forward_fn()
  File "/root/ghl/distiller/examples/auto_compression/amc/utils/net_wrapper.py", line 167, in validate
    top1, top5, vloss = self.services.validate_fn(model=self.model)
  File "/root/ghl/distiller/distiller/apputils/image_classifier.py", line 657, in test
    torch.onnx.export(non_para_model, dummy_input, onnx_fname)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/utils.py", line 249, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/onnx/utils.py", line 206, in _trace_and_get_graph_from_model
    trace, torch_out, inputs_states = torch.jit.get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/jit/__init__.py", line 275, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/jit/__init__.py", line 352, in forward
    out = self.inner(*trace_inputs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/ghl/distiller/distiller/apputils/image_classifier.py", line 655, in <lambda>
    non_para_model.forward = lambda input: softmax(non_para_model.original_forward(input))
  File "/root/ghl/distiller/distiller/models/cifar10/resnet_cifar.py", line 142, in forward
    x = self.layer1(x)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/ghl/distiller/distiller/models/cifar10/resnet_cifar.py", line 77, in forward
    out = self.conv2(out)
  File "/root/ghl/dis/lib/python3.5/site-packages/torch/nn/modules/module.py", line 543, in __call__
    hook_result = hook(self, input, result)
  File "/root/ghl/distiller/distiller/pruning/ranked_structures_pruner.py", line 606, in cache_featuremaps_fwd_hook
    pts = randx * w_out + randy
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray`

I find a problem in log file, the torchvision version is "0.4.2+cu9.2" while I used cuda9.0. Is this  the reason to cause the problem?

**Comment by smxzxcghl** [comment]
hi @nzmora 
I found the reason that I add a code block in image_classifier.py to export the pruned model to onnx The code worked when I use pruning methods except amc . After I erase the code block amc worked successfully. 
Thanks for reminding me. Could you please give me some advice on exporting amc model to Onnx？

**Comment by nzmora** [comment]
Hi @smxzxcghl,

You can take an AMC-generated model and export it to ONNX using [this](https://github.com/NervanaSystems/distiller/wiki/Distiller-Summary-Reports#onnx).
Also, you can write your own code to export to ONNX - the code is pretty straight-forward:
https://github.com/NervanaSystems/distiller/blob/34f9a55b68a588fcc8325dfc37534f12ef358673/distiller/model_summaries.py#L459-L481

Cheers,
Neta

**Comment by smxzxcghl** [comment]
hi @nzmora 
I have exported amc-generated model to onnx successfully.You gave me such useful advice. Thank you for your help. Now I close this issue.
