### ISSUE TITLE
Error in resume quantize checkpoint

### ISSUE THREAD

**Issue by chenys1995** [NervanaSystems/distiller#49]
https://github.com/NervanaSystems/distiller/blob/e749ea6288431a53f839b621cc3e38facbf824de/distiller/quantization/range_linear.py#L165
I got an error message after resume symmetric linear quantized model
```
Traceback (most recent call last):
  File "compress_classifier.py", line 684, in <module>
    main()
  File "compress_classifier.py", line 244, in main
    model, chkpt_file=args.resume)
  File "/chenys/distiller/apputils/checkpoint.py", line 116, in load_checkpoint
    quantizer = qmd['type'](model, **qmd['params'])
TypeError: __init__() got an unexpected keyword argument 'bits_weights'
```
I modify the `__init__ ` argument and fix the problem
```python
def __init__(self, model, bits_activations=8, bits_weights=8, **kw):
     super(SymmetricLinearQuantizer, self).__init__(model, bits_activations=bits_activations,
                                                    bits_weights=bits_weights, 
                                                    train_with_fp_copy=False,
                                                    **kw)
```
I think the quantizer may be consistent in naming the parameters, or the quantizer_metadata will cause initialize error

**Comment by guyjacob** [comment]
@chenys1995 this is a bug indeed - thanks for catching it! Your modification looks fine as well. Would you mind making a pull request with the fix? If that's not an option, let me know and I'll push the fix myself.
