### ISSUE TITLE
Quantization statistics collector produce no inputs in few layers

### ISSUE THREAD

**Issue by lukino563** [NervanaSystems/distiller#501]
I have problem with stats collector. I have custom implemented YOLOv3 in Darknet and it has EmptyLayers as route or shortcut but collector produces somthing like this and post training quantization fails on processing that yaml file:
`module_list.17.route_17:
  output:
    min: 1.7976931348623157e+308
    max: -1.7976931348623157e+308
    avg_min: 0
    avg_max: 0
    mean: 0
    std: 0
    b: 0
    shape: ''
    total_numel: 0`

If I manually remove it from stats it works, can I ommit this in code ?
Error produced on post quantization with that generated stats file:
`Traceback (most recent call last):
  File "quantize_yolov3.py", line 145, in <module>
    main()
  File "quantize_yolov3.py", line 130, in main
    quantizer.prepare_model(dummy_input)
  File "/home/fedora/Projects/Python/distiller/distiller/quantization/range_linear.py", line 1969, in prepare_model
    super(PostTrainLinearQuantizer, self).prepare_model(dummy_input)
  File "/home/fedora/Projects/Python/distiller/distiller/quantization/quantizer.py", line 240, in prepare_model
    self._pre_process_container(self.model)
  File "/home/fedora/Projects/Python/distiller/distiller/quantization/quantizer.py", line 343, in _pre_process_container
    self._pre_process_container(module, full_name + '.')
  File "/home/fedora/Projects/Python/distiller/distiller/quantization/quantizer.py", line 343, in _pre_process_container
    self._pre_process_container(module, full_name + '.')
  File "/home/fedora/Projects/Python/distiller/distiller/quantization/quantizer.py", line 321, in _pre_process_container
    new_module = replace_fn(module, full_name, self.module_qbits_map, **valid_kwargs)
  File "/home/fedora/Projects/Python/distiller/distiller/quantization/range_linear.py", line 1751, in replace_fake_quant
    quantize_inputs=quantize_inputs)
  File "/home/fedora/Projects/Python/distiller/distiller/quantization/range_linear.py", line 1459, in __init__
    inputs_quant_auto_fallback=inputs_quant_auto_fallback)
  File "/home/fedora/Projects/Python/distiller/distiller/quantization/range_linear.py", line 465, in __init__
    for idx, stats in activation_stats['inputs'].items():
KeyError: 'inputs'
`

Thank you

**Comment by lukino563** [comment]
fixed it already, my bad, module was not used in model forward func, so it was not producing inputs
