### ISSUE TITLE
Model loading errors after quantization

### ISSUE THREAD

**Issue by Raso527** [NervanaSystems/distiller#509]
Hello, when I loaded the model into it after training it as follows, I got an error.
In this case, how should I deal with it?

training command

` $ python compress_classifier.py --arch simplenet_cifar /torch/datasets/ -p=50 --epochs=3 --compress=../quantization/quant_aware_train/simplenet_cifar_dorefa.yaml -j 22 --lr 0.001 --wd 0.001 --vs 0
`
yaml file component

quantizers:
  dorefa_quantizer:
    class: DorefaQuantizer
    bits_activations: 4
    bits_weights: 4

lr_schedulers:
  training_lr:
    Class: MultiStepLR
    MILESTONES: [60, 75]
    gamma: 0.2

Policies:
    - Quantizer:
        instance_name: dorefa_quantizer
      Starting_epoch: 0
      ending_epoch: 200
      frequency: 1
    - lr_scheduler:
        instance_name: training_lr
      Starting_epoch: 0
      ending_epoch: 200
      frequency: 1

retraining command

`
python compress_classifier.py --arch simplenet_cifar /torch/datasets/ -p=50 --epochs=3 --exp-load-weights-from=logs/2020.05.12-150829/best.pth.tar --compress=.. /quantization/quant_aware_train/simplenet_cifar_dorefa.yaml -j 22 --lr 0.001 --wd 0.0001 --vs 0
`

errors

Traceback (most recent call last):
  File "compress_classifier.py", line 220, in <module>
    main()
  File "compress_classifier.py", line 74, in main
    app = ClassifierCompressorSampleApp(args, script_dir=os.path.dirname(__file__))
  File "compress_classifier.py", line 172, in __init__
    super().__init__(args, script_dir)
  File "/mnt/distiller/apputils/image_classifier.py", line 71, in __init__
    self.start_epoch, self.ending_epoch) = _init_learner(self.args)
  File "/mnt/distiller/apputils/image_classifier.py", line 402, in _init_learner
    model = apputils.load_lean_checkpoint(model, args.load_model_path, model_device=args.device)
  File "/mnt/distiller/apputils/checkpoint.py", line 92, in load_lean_checkpoint
    lean_checkpoint=True)[0]
  File "/mnt/distiller/apputils/checkpoint.py", line 224, in load_checkpoint
    quantizer = qmd['type'](model, **qmd['params'])
TypeError: __init__() missing 1 required positional argument: 'optimizer'

best,
Raso

**Comment by Akimoto-Cris** [comment]
I encountered the same problem before. Please consider trying out my solution in #535
